Running 1 test case...
Entering test module "Player_test"
../src/Player_test.cpp(114): Entering test case "two_files"
../src/Player_test.cpp(117): info: check 'no exceptions thrown by player.setPlaylist(getTestPlaylist_3())' has passed
../src/Player_test.cpp(114): Leaving test case "two_files"; testing time: 10175975us
Leaving test module "Player_test"; testing time: 10176060us
